services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: redis:latest
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api_customer_favorites
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/
      - REDIS_URI=redis://cache_redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
